apiVersion: v1
kind: Namespace
metadata:
  name: fast-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-test-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: python-test-app
  template:
    metadata:
      labels:
        app: python-test-app
    spec:
      containers:
      - image: localhost:32000/python-test-app
        name: python-test-app
        ports:
        - containerPort: 8001