apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-test-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
  project: python-fast-api
  source:
    path: apps/python-test-app
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
        - values-prod.yaml
  # syncPolicy:
  #     automated:
  #       prune: true
  #       self-heal: true