apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-test-app-np
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: fast-api
  project: python-fast-api
  source:
    path: apps/python-test-app
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      values: |
        enviorment: np
  syncPolicy:
      automated:
        prune: true
      syncOptions:
        - CreateNamespace=false