apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-test-app
  namespace: argocd
spec:
  destination:
    namespace: fast-api
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/python-test-app
    repoURL: https://github.com/jordanthomas761/python-test-app
    targetRevision: main