apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-test-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: fast-api
    name: https://kubernetes.default.svc
  project: default
  source:
    path: apps/python-test-app
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}