apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-test-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: fast-api
    name: in-cluster
  project: python-test-app
  source:
    path: apps/python-test-app
    repoURL: https://github.com/jordanthomas761/python-test-app
    targetRevision: HEAD