apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-test-app-ingress
  namespace: fast-api-{{ .Values.enviorment }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    argocd.argoproj.io/sync-wave: "1"
spec:
  rules:
  - http:
      paths:
      - path: /fast-api-{{ .Values.enviorment }}/?(.*)
        pathType: Prefix
        backend:
          service:
            name: python-test-app
            port:
              number: 8001