apiVersion: v1
kind: Service
metadata:
  name: python-test-app-{{ .Values.enviorment }}
  namespace: fast-api
spec:
  type: NodePort
  selector:
    app: python-test-app-{{ .Values.enviorment }}
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001