apiVersion: v1
kind: Service
metadata:
  name: python-test-app
  namespace: fast-api-{{ .Values.enviorment }}
spec:
  type: NodePort
  selector:
    app: python-test-app
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001