apiVersion: v1
kind: Service
metadata:
  name: python-test-app-{{ .Values.enviorment }}
  namespace: fast-api
spec:
  selector:
    app: python-test-app-prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001