on: [ workflow_dispatch]

jobs:
  build-app:
    runs-on: self-hosted
    name: build app
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: build app
        working-directory: python-test-app
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/python-test-app:${{ github.sha }} .
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: upload app
        working-directory: python-test-app
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/python-test-app:${{ github.sha }}
