on: push

jobs:
  build-app:
    runs-on: self-hosted
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: build app
        working-directory: python-test-app
        run: docker build -t registry.container-registry.svc.cluster.local:32000/python-test-app .
      - name: upload app
        working-directory: python-test-app
        run: docker push registry.container-registry.svc.cluster.local:32000/python-test-app